name = "our-family-reunion"
main = "api/index.js"
compatibility_date = "2024-01-01"

[vars]

[[d1_databases]]
binding = "DB"
database_name = "reunionite"
database_id = "0fbf49c6-2797-4e2e-89df-a4de7dbbc879"


  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "42b29a5e8cb947c58cec90ce7f4a25e2",
      
      // Optional: preview_id used when running `wrangler dev` for local dev
      "preview_id": "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
    }
  ]
